spring:
  application:
    name: ai-error-analyzer
  redis:
    host: ${REDIS_HOST:team2-talkking-dev-redis.9iaedf.ng.0001.apn2.cache.amazonaws.com}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000ms
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: -1ms
  datasource:
    url: ${DB_URL}

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true



errorops:
  kubernetes:
    log-tail-lines: 120
  gemini:
    model: ${GEMINI_MODEL:gemini-flash-latest}
    api-key: ${GEMINI_API_KEY:}
  slack:
    general-webhook-url: ${SLACK_GENERAL_WEBHOOK_URL:}
    critical-webhook-url: ${SLACK_CRITICAL_WEBHOOK_URL:}
    warning-webhook-url: ${SLACK_WARNING_WEBHOOK_URL:}
    info-webhook-url: ${SLACK_INFO_WEBHOOK_URL:}



logging:
  level:
    com.team2.talkking.errorops.alert: INFO
    org.springframework.data.redis: WARN
